### PR TITLE
initial support for s390x

### LINKED ISSUE #41: s390x support
We are working on building k3s-root on s390x, since we need the binaries generated in k3s-root in order to build rke2 on s390x. Unfortunately, buildroot doesn't support static builds on s390x https://bugs.busybox.net/show_bug.cgi?id=14256 
Would it be possible to use shared libraries instead of static?

### PR DESCRIPTION
**Pull request by dweomer**
- Compile buildroot on alpine 3.14
- Initial support for s390x
- Cleaned up some scripts: Thanks, shell-check.

Fixes #41 

Signed-off-by: Jacob Blain Christen <jacob@rancher.com>

### CODE REVIEW

**Comment by dweomer** [comment]
```shell
$ find artifacts/s390x/bin -type f -exec file {} \;
artifacts/s390x/bin/pigz: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/charon: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/fuse-overlayfs: ELF 64-bit MSB executable, IBM S/390, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=bec09eae70531dbb8f474d36411ee871658fe8ab, with debug_info, not stripped
artifacts/s390x/bin/swanctl: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/busybox: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/ethtool: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/coreutils: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/ip: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/aux/ebtables-legacy: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/aux/iptables-detect.sh: POSIX shell script, ASCII text executable
artifacts/s390x/bin/aux/iptables-apply: Bourne-Again shell script, ASCII text executable
artifacts/s390x/bin/aux/xtables-legacy-multi: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/aux/ebtablesu: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/aux/ebtablesd: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/aux/xtables-set-mode.sh: POSIX shell script, ASCII text executable
artifacts/s390x/bin/aux/xtables-nft-multi: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/slirp4netns: ELF 64-bit MSB executable, IBM S/390, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=9131e1c43056a14bbf74746d025efd4714b79840, with debug_info, not stripped
artifacts/s390x/bin/conntrack: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/ipset: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/nsenter: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/losetup: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/blkid: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/socat: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
artifacts/s390x/bin/find: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, stripped
```

**Comment by kravciak** [comment]
Build fails for me on s390 (SLES 15-SP2), did you encounter this problem?
```
+ ./build
+ pushd /usr/src/buildroot
/usr/src/buildroot ~/scripts
+ cp -rfv /source/package/busybox /source/package/conntrack-tools /source/package/iptables /source/package/strongswan package/
'/source/package/busybox/busybox.config' -> 'package/busybox/busybox.config'
'/source/package/conntrack-tools/0001-static.patch' -> 'package/conntrack-tools/0001-static.patch'
'/source/package/conntrack-tools/Config.in' -> 'package/conntrack-tools/Config.in'
'/source/package/conntrack-tools/conntrack-tools.hash' -> 'package/conntrack-tools/conntrack-tools.hash'
'/source/package/conntrack-tools/conntrack-tools.mk' -> 'package/conntrack-tools/conntrack-tools.mk'
'/source/package/iptables/0001-static-init_extensions6.patch' -> 'package/iptables/0001-static-init_extensions6.patch'
'/source/package/strongswan/Config.in' -> 'package/strongswan/Config.in'
'/source/package/strongswan/strongswan.hash' -> 'package/strongswan/strongswan.hash'
'/source/package/strongswan/strongswan.mk' -> 'package/strongswan/strongswan.mk'
+ cp /source/buildroot/config /usr/src/buildroot/.config
+ cp /source/buildroot/s390xconfig /usr/src/buildroot/.config-arch
+ cat .config-arch
+ make -s oldconfig
make: /bin/sh: Operation not permitted
make: -c: Operation not permitted
make: -c: Operation not permitted
make: -c: Operation not permitted
make: *** [Makefile:84: _all] Error 127
FATA[0007] exit status 2                                
make: *** [Makefile:16: ci] Error 1
```

**Comment by dweomer** [comment]
> > Build fails for me on s390 (SLES 15-SP2), did you encounter this problem?

Oh, just grokked this detail. Err, you are running in some kind of container right? Something else that might be trapping unknown syscalls and instead of returning ENOSYS its returning EPERM?

Or, since we're talking SLES here, maybe it's AppArmor being the jerk :thinking:

**Review by brandond — APPROVED** [review]
LGTM. One question about the download script bit.

Might we also think about including the wireguard userspace? We've got all the stuff in here for the flannel ipsec backend, but we support the wireguard backend while requiring the user to provide the userspace which seems odd.

**Comment by dweomer** [comment]
> Might we also think about including the wireguard userspace? We've long had all the stuff in here for the flannel ipsec backend, but we support the wireguard backend while requiring the user to provide the userspace which seems odd.

That's a good idea, suitable for a different PR. There are a number of issues that I would like to address before cutting a new GA release of this repo:
- inclusion of wireguard userspace for those platforms that it supports (if not all)
- strip slirp4netns binary
- strip fuse-overlayfs binary
- bump to latest lts buildroot
- feedback from suse/z folks on whether s390x actually works

**Comment by thehejik** [comment]
> > Build fails for me on s390 (SLES 15-SP2), did you encounter this problem?
> ```
> docker run -it --security-opt seccomp=unconfined ...
> ```
Thanks, this really solves the build issue on SLE15-SP2/s390x VM - it is needed whenever AppArmor is running or not.
```
diff --git a/Dockerfile.dapper b/Dockerfile.dapper
index 41db665..ec193d0 100644
--- a/Dockerfile.dapper
+++ b/Dockerfile.dapper
@@ -36,7 +36,7 @@ RUN set -eux \
 ENV DAPPER_SOURCE /source
 ENV DAPPER_OUTPUT ./artifacts ./dist
 ENV DAPPER_ENV BUILDARCH
-ENV DAPPER_RUN_ARGS -v k3s-root-cache:/var/cache/dl
+ENV DAPPER_RUN_ARGS -v k3s-root-cache:/var/cache/dl --security-opt seccomp=unconfined
 ENV BR2_DL_DIR /var/cache/dl 
 # Required to build as root, even in Docker
 ENV FORCE_UNSAFE_CONFIGURE 1 
```

**Review by brandond — APPROVED** [review]

**Pull request merged**
